import {summary} from './finance.js';
import {activeItems,quantity,lineTotal,cartTotal,demoCommand} from './inventory.js';
export function createWorkflows(ctx){
 const {esc,money,cents,today,validateExpense}=ctx;
 const options=(arr,value)=>arr.map(c=>`<option ${c===value?'selected':''}>${esc(c)}</option>`).join('');
 const numeric=(name,label,value=0,min=0)=>`<label>${label}<input name="${name}" type="number" inputmode="decimal" min="${min}" max="1000000" step="0.001" value="${esc(value)}" required></label>`;
 async function command(action,payload){
  if(ctx.isDemo())demoCommand(ctx.getData(),action,payload);
  else{const {error}=await ctx.db.rpc('market_command',{p_household:ctx.getData().household.id,p_action:action,p_data:payload});if(error)throw error;}
 }
 async function refresh(){if(ctx.isDemo())ctx.render();else await ctx.load();}
 function modal(title,fields,submit,button='Guardar'){
  const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(title)}</h2><form><div class="form-grid">${fields}</div><p class="notice error" role="alert" hidden></p><div class="actions"><button type="button" class="secondary">Cancelar</button><button type="submit">${esc(button)}</button></div></form>`;
  document.body.append(d);d.showModal();d.querySelector('[type="button"]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());let saving=false;
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;const b=d.querySelector('[type="submit"]');b.disabled=true;try{await submit(new FormData(e.target));d.close();await refresh();}catch(error){const p=d.querySelector('[role="alert"]');p.hidden=false;p.textContent=error.code==='23505'?'Ya existe ese producto o movimiento. Actualiza la lista.':error.message||'No se pudo guardar.';}finally{saving=false;b.disabled=false;}};
  return d;
 }
 function showHistory(title,html){const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(title)}</h2>${html}<div class="actions"><button>Cerrar</button></div>`;document.body.append(d);d.showModal();d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());}
 function editExpense(id){
  const e={...ctx.getData().expenses.find(x=>x.id===id)};const fund=ctx.getData().funds.find(f=>f.id===e.fund_id);
  modal('Modificar gasto',`<p class="wide muted">Se actualizará el saldo de ${esc(fund.name)}. Se conservará el historial. Si es una compra, este ajuste no modifica las existencias.</p><label class="wide">Concepto<input name="description" maxlength="160" value="${esc(e.description)}" required></label><label>Fecha del gasto<input name="occurred_on" type="date" min="${esc(fund.starts_on)}" max="${today()}" value="${esc(e.occurred_on)}" required></label><label>Importe (MXN)<input name="amount" type="number" inputmode="decimal" min="0.01" max="1000000" step="0.01" value="${e.amount_cents/100}" required></label><label>Categoría<select name="category">${options([...new Set([...ctx.categories,e.category])],e.category)}</select></label><label>Medio<select name="method"><option value="card" ${e.method==='card'?'selected':''}>Tarjeta</option>${fund.kind==='voucher'?'':`<option value="cash" ${e.method==='cash'?'selected':''}>Efectivo</option>`}</select></label>`,async f=>{
   const x={id:e.id,version:e.revision||1,description:f.get('description').trim(),amount_cents:cents(f.get('amount')),occurred_on:f.get('occurred_on'),method:f.get('method'),category:f.get('category')};validateExpense(x,fund);await command('expense_edit',x);
  },'Guardar corrección');
 }
 function linkExpense(id){
  const data=ctx.getData(),expense=data.expenses.find(e=>e.id===id);
  if(data.inventory_events.some(v=>v.expense_id===id)){showHistory('Productos ya vinculados','<p>Este gasto ya actualizó existencias. Consulta el historial del producto en Inventario.</p>');return;}
  if(!data.products.length){showHistory('Agrega productos','<p>Primero crea el producto en Inventario; después vuelve al gasto para vincularlo.</p>');return;}
  const row=()=>`<div class="wide expense-product-line"><label>Producto<select name="product_id">${data.products.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} (${esc(p.unit)})</option>`).join('')}</select></label>${numeric('quantity','Unidades que faltan en inventario',1,0.001)}</div>`;
  const d=modal('Productos de '+expense.description,`<p class="wide muted">Este gasto ya descontó dinero. Agrega solo las unidades que realmente conservas y que aún no figuran en Inventario. No se cobrará de nuevo.</p><div class="wide" id="expense-lines">${row()}</div><button class="secondary wide" type="button" id="another-product">+ Otro producto</button>`,async f=>{
   const lines=[...d.querySelectorAll('.expense-product-line')].map(el=>({product_id:el.querySelector('[name="product_id"]').value,quantity:quantity(el.querySelector('[name="quantity"]').value,{zero:false})}));
   if(new Set(lines.map(l=>l.product_id)).size!==lines.length)throw new Error('Selecciona cada producto una sola vez.');
   if(ctx.isDemo())await command('link_expense_items',{expense_id:id,lines});
   else{const {error}=await ctx.db.rpc('link_expense_inventory',{p_household:data.household.id,p_expense:id,p_lines:lines});if(error)throw error;}
  },'Vincular al inventario');
  d.querySelector('#another-product').onclick=()=>d.querySelector('#expense-lines').insertAdjacentHTML('beforeend',row());
 }
 function expenseHistory(id){const rows=ctx.getData().expense_history.filter(x=>x.expense_id===id).sort((a,b)=>b.created_at.localeCompare(a.created_at));showHistory('Historial del gasto',rows.map(x=>`<div class="history-entry"><strong>${esc(x.actor_name)}</strong> · ${esc(new Date(x.created_at).toLocaleString('es-MX'))}<p>Fecha: ${esc(x.before_data.occurred_on)} → ${esc(x.after_data.occurred_on)}<br>Importe: ${money(x.before_data.amount_cents)} → ${money(x.after_data.amount_cents)}<br>Concepto: ${esc(x.before_data.description)} → ${esc(x.after_data.description)}<br>Categoría: ${esc(x.before_data.category)} → ${esc(x.after_data.category)}<br>Medio: ${esc(x.before_data.method)} → ${esc(x.after_data.method)}</p></div>`).join('')||'<p class="muted">Este gasto todavía no tiene correcciones.</p>');}
 function productForm(id){
  const p=id?{...ctx.getData().products.find(p=>p.id===id)}:null;const pid=p?.id||crypto.randomUUID();
  modal(p?'Editar producto':'Añadir producto',`<label class="wide">Nombre<input name="name" maxlength="120" required value="${esc(p?.name||'')}"></label><label>Categoría<select name="category">${options(categories,p?.category)}</select></label><label>Unidad<select name="unit">${options(['unidad','pieza','litro','kg','rollo','botella'],p?.unit||'unidad')}</select></label>${p?'<p class="wide muted">Para cambiar existencias utiliza «Registrar consumo / ajuste».</p>':numeric('on_hand','Existencias actuales',0)}${numeric('minimum','Avisar cuando queden',p?.minimum||0)}${numeric('target','Cantidad objetivo',p?.target||0)}`,async f=>{
   const minimum=quantity(f.get('minimum')),target=quantity(f.get('target'));if(target<minimum)throw new Error('El objetivo no puede ser menor al mínimo.');
   await command('product_save',{id:pid,version:p?.version??null,name:f.get('name').trim(),category:f.get('category'),unit:f.get('unit'),minimum,target,...(!p?{on_hand:quantity(f.get('on_hand'))}:{})});
  });
 }
 function stockForm(id){const p={...ctx.getData().products.find(p=>p.id===id)};
  modal('Registrar consumo / ajuste',`<p class="wide muted">${esc(p.name)} · Disponible: <strong>${p.on_hand} ${esc(p.unit)}</strong></p><label class="wide">Tipo<select name="type"><option value="consume">Consumo</option><option value="waste">Desperdicio</option><option value="adjust">Corregir existencia total</option></select></label>${numeric('quantity','Cantidad',1)}<label>Nota<input name="note" maxlength="120" placeholder="Opcional"></label>`,async f=>{
   const amount=quantity(f.get('quantity'));const type=f.get('type');const delta=type==='adjust'?amount-p.on_hand:-amount;if(delta===0)throw new Error('La cantidad debe producir un cambio.');if(p.on_hand+delta<0)throw new Error('No puedes descontar más de lo disponible.');await command('stock_adjust',{id:p.id,version:p.version,delta:Math.round(delta*1000)/1000,reason:({consume:'Consumo',waste:'Desperdicio',adjust:'Corrección'})[type]+(f.get('note').trim()?': '+f.get('note').trim():'')});
  });
 }
 function stockHistory(id){const rows=ctx.getData().inventory_events.filter(x=>x.product_id===id).sort((a,b)=>b.created_at.localeCompare(a.created_at));showHistory('Movimientos de inventario',rows.map(x=>`<div class="history-entry"><strong>${esc(x.reason)}</strong><p>${Number(x.delta)>0?'+':''}${x.delta} · Existencia: ${x.balance}<br><small>${esc(x.actor_name)} · ${esc(new Date(x.created_at).toLocaleString('es-MX'))}</small></p></div>`).join('')||'<p>Sin movimientos.</p>');}
 function addShopping(productId){const products=ctx.getData().products;if(!products.length){productForm();return;}
  modal('Añadir a la lista',`<label class="wide">Producto<select name="product_id">${products.map(p=>`<option value="${esc(p.id)}" ${p.id===productId?'selected':''}>${esc(p.name)} (${esc(p.unit)})</option>`).join('')}</select></label>${numeric('quantity','Cantidad a comprar',1,0.001)}<p class="wide muted">Si el producto ya está pendiente, se conserva su cantidad. Puedes editarla en la lista.</p>`,async f=>command('shopping_add',{product_id:f.get('product_id'),quantity:quantity(f.get('quantity'),{zero:false})}));
 }
 function editShopping(id){const item={...ctx.getData().shopping_items.find(x=>x.id===id)};const p=ctx.getData().products.find(p=>p.id===item.product_id);
  modal(p.name,`${numeric('quantity',`Cantidad (${esc(p.unit)})`,item.quantity,0.001)}<label>Precio por ${esc(p.unit)} (MXN)<input name="price" type="number" min="0" max="1000000" step="0.01" inputmode="decimal" value="${item.unit_price_cents===null?'':item.unit_price_cents/100}"></label><label class="wide">Estado<select name="state"><option value="pending" ${item.state==='pending'?'selected':''}>Pendiente</option><option value="cart" ${item.state==='cart'?'selected':''}>En el carrito</option><option value="removed">Quitar de la lista</option></select></label><p class="wide muted">Al editar, la cantidad deja de ajustarse automáticamente por inventario.</p>`,async f=>{
   const price=f.get('price');const unit_price_cents=price===''?null:Number(price)===0?0:cents(price);await command('shopping_edit',{id:item.id,version:item.version,quantity:quantity(f.get('quantity'),{zero:false}),unit_price_cents,state:f.get('state')});
  });
 }
 async function toggleCart(id,button){const s={...ctx.getData().shopping_items.find(x=>x.id===id)};button.disabled=true;try{await command('shopping_edit',{id:s.id,version:s.version,quantity:s.quantity,unit_price_cents:s.unit_price_cents,state:s.state==='cart'?'pending':'cart'});await refresh();}catch(error){button.disabled=false;showHistory('No se pudo actualizar',`<p>${esc(error.message)}</p>`);}}
 function checkout(){
  const rows=activeItems(ctx.getData()).filter(x=>x.state==='cart').map(x=>({...x}));if(!rows.length){showHistory('Carrito vacío','<p>Marca primero los productos que llevas.</p>');return;}
  let total;try{total=cartTotal(rows);if(total<=0)throw new Error('El total debe ser mayor a cero.');}catch(error){showHistory('Revisa los precios',`<p>${esc(error.message)}</p>`);return;}
  const id=crypto.randomUUID();const funds=ctx.getData().funds;
  const d=modal('Confirmar compra',`<p class="wide">${rows.length} productos · Total <strong>${money(total)}</strong></p><label class="wide">Concepto<input name="description" value="Compra del hogar" maxlength="160" required></label><label>Fondo<select name="fund_id">${funds.map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('')}</select></label><label>Medio<select name="method"><option value="card">Tarjeta</option><option value="cash">Efectivo</option></select></label><label class="wide">Fecha<input type="date" name="occurred_on" value="${today()}" max="${today()}" required></label><p id="checkout-budget" class="wide notice"></p><p class="wide muted">Solo lo que está en el carrito se registrará como gasto y entrará al inventario. Los demás productos seguirán pendientes.</p>`,async f=>{
   const x={id,description:f.get('description').trim(),fund_id:f.get('fund_id'),method:f.get('method'),occurred_on:f.get('occurred_on'),total_cents:total,lines:rows.map(r=>({id:r.id,version:r.version}))};validateExpense(x,funds.find(f=>f.id===x.fund_id));await command('checkout',x);
  },'Confirmar y guardar compra');
  const form=d.querySelector('form');const enforce=()=>{const fund=funds.find(f=>f.id===form.elements.fund_id.value);const voucher=fund?.kind==='voucher';const available=summary(fund,ctx.getData().expenses,ctx.getData().reservations,ctx.periodEnd()).available;d.querySelector('#checkout-budget').textContent=available<total?'Este fondo tiene '+money(available)+' disponibles; faltan '+money(total-available)+'. No se moverá dinero de otro fondo.':'Disponible en este fondo: '+money(available)+'. Después de la compra: '+money(available-total)+'.';form.elements.method.querySelector('[value="cash"]').disabled=voucher;if(voucher)form.elements.method.value='card';};form.elements.fund_id.onchange=enforce;enforce();
 }
 function inventoryView(){const data=ctx.getData();const products=[...data.products].sort((a,b)=>a.name.localeCompare(b.name));const low=products.filter(p=>Number(p.on_hand)<=Number(p.minimum));return `<div class="section-title"><span class="pill">${products.length} productos · ${low.length} por terminar</span><button data-action="new-product">+ Añadir producto</button></div><p class="subtle muted">Define el mínimo y el objetivo para generar la reposición automática. Las cantidades que edites en la lista se respetan.</p><div class="inventory-grid">${products.map(p=>`<article class="card"><div class="section-title"><span class="pill ${Number(p.on_hand)<=Number(p.minimum)?'warning':''}">${Number(p.on_hand)<=Number(p.minimum)?'Por terminar':'Disponible'}</span><button class="text" data-product-edit="${esc(p.id)}">Editar</button></div><h2>${esc(p.name)}</h2><small>${esc(p.category)}</small><div class="amount">${Number(p.on_hand)} <small>${esc(p.unit)}</small></div><p class="subtle muted">Mínimo ${Number(p.minimum)} · Objetivo ${Number(p.target)}</p><div class="product-actions"><button class="secondary" data-stock="${esc(p.id)}">Consumo / ajuste</button><button class="text" data-add-product="${esc(p.id)}">A la lista</button><button class="text" data-stock-history="${esc(p.id)}">Historial</button></div></article>`).join('')||'<section class="card empty">Añade lo que tienes en casa para comenzar.</section>'}</div>`;}
 function shoppingView(){const data=ctx.getData(),items=activeItems(data);const cart=items.filter(s=>s.state==='cart');const known=cart.filter(s=>s.unit_price_cents!==null).reduce((s,x)=>s+lineTotal(x),0);return `<div class="section-title"><span class="pill">${items.length} productos pendientes</span><button data-action="add-shopping">+ Añadir a la lista</button></div><div class="card cart-summary"><div><small>En el carrito · ${cart.length} productos</small><div class="amount">${money(known)}</div>${cart.some(x=>x.unit_price_cents===null)?'<span class="negative">Total parcial: faltan precios</span>':''}</div><button data-action="checkout" ${cart.length?'':'disabled'}>Finalizar compra</button></div><section class="card">${items.map(s=>{const p=data.products.find(p=>p.id===s.product_id);return `<div class="shopping-row"><button class="cart-check ${s.state==='cart'?'checked':''}" data-toggle-cart="${esc(s.id)}" aria-label="${s.state==='cart'?'Sacar':'Poner'} ${esc(p.name)} ${s.state==='cart'?'del':'en el'} carrito">${s.state==='cart'?'✓':'+'}</button><div class="row-main"><strong>${esc(p.name)}</strong><small>${Number(s.quantity)} ${esc(p.unit)} · ${s.automatic?'Reposición automática':'Cantidad manual'}</small><small>${s.unit_price_cents===null?'Precio pendiente':money(s.unit_price_cents)+' por '+esc(p.unit)}</small></div><div class="row-amount"><strong>${s.unit_price_cents===null?'—':money(lineTotal(s))}</strong><br><button class="text" data-shopping-edit="${esc(s.id)}">Editar</button></div></div>`;}).join('')||'<div class="empty">Tu lista está vacía. Añade productos o configura sus mínimos.</div>'}</section>`;}
 function bind(){
  const bindAll=(selector,fn)=>document.querySelectorAll(selector).forEach(b=>b.onclick=()=>fn(b));
  bindAll('[data-expense-stock]',b=>linkExpense(b.dataset.expenseStock));bindAll('[data-expense-edit]',b=>editExpense(b.dataset.expenseEdit));bindAll('[data-expense-history]',b=>expenseHistory(b.dataset.expenseHistory));
  bindAll('[data-product-edit]',b=>productForm(b.dataset.productEdit));bindAll('[data-stock]',b=>stockForm(b.dataset.stock));bindAll('[data-stock-history]',b=>stockHistory(b.dataset.stockHistory));bindAll('[data-add-product]',b=>addShopping(b.dataset.addProduct));
  bindAll('[data-shopping-edit]',b=>editShopping(b.dataset.shoppingEdit));bindAll('[data-toggle-cart]',b=>toggleCart(b.dataset.toggleCart,b));
  bindAll('[data-action]',b=>({'new-product':()=>productForm(),'add-shopping':()=>addShopping(),'checkout':checkout}[b.dataset.action]?.()));
 }
 return {inventoryView,shoppingView,bind};
}
