import {summary} from './finance.js';
import {activeItems,quantity,lineTotal,cartTotal,demoCommand} from './inventory.js';
import {stockStatus} from './stock-status.js';
import {smartItems,itemTotal,priorityOrder,priorityLabel,cartBreakdown,budgetMessages,consumptionEstimate,demoSmartCommand} from './smart-shopping.js';
import {applyWalmartMatch,findWalmartPrice,walmartQueryFor} from './walmart-price.js';
export function createWorkflows(ctx){
 const {esc,money,cents,today,validateExpense,categories}=ctx;
 const options=(arr,value)=>arr.map(c=>`<option ${c===value?'selected':''}>${esc(c)}</option>`).join('');
 const numeric=(name,label,value=0,min=0)=>`<label>${label}<input name="${name}" type="number" inputmode="decimal" min="${min}" max="1000000" step="0.001" value="${esc(value)}" required></label>`;
 async function command(action,payload){
  if(ctx.isDemo())demoCommand(ctx.getData(),action,payload);
  else{const {error}=await ctx.db.rpc('market_command',{p_household:ctx.getData().household.id,p_action:action,p_data:payload});if(error)throw error;}
 }
 async function smartCommand(action,payload){
  if(ctx.isDemo())demoSmartCommand(ctx.getData(),action,payload);
  else{const {error}=await ctx.db.rpc('smart_shopping_command',{p_household:ctx.getData().household.id,p_action:action,p_data:payload});if(error)throw error;}
 }
 async function refresh(){if(ctx.isDemo())ctx.render();else await ctx.load();}
 function modal(title,fields,submit,button='Guardar'){
  const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(title)}</h2><form><div class="form-grid">${fields}</div><p class="notice error" role="alert" hidden></p><div class="actions"><button type="button" class="secondary">Cancelar</button><button type="submit">${esc(button)}</button></div></form>`;
  document.body.append(d);d.showModal();d.querySelector('[type="button"]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());let saving=false;
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(saving)return;saving=true;const b=d.querySelector('[type="submit"]');b.disabled=true;try{await submit(new FormData(e.target));d.close();await refresh();}catch(error){const p=d.querySelector('[role="alert"]');p.hidden=false;p.textContent=error.code==='23505'?'Ya existe ese producto o movimiento. Actualiza la lista.':error.message||'No se pudo guardar.';}finally{saving=false;b.disabled=false;}};
  return d;
 }
 function showHistory(title,html){const d=document.createElement('dialog');d.innerHTML=`<h2>${esc(title)}</h2>${html}<div class="actions"><button>Cerrar</button></div>`;document.body.append(d);d.showModal();d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());}
 function editExpense(id){
  const e={...ctx.getData().expenses.find(x=>x.id===id)};const fund=ctx.getData().funds.find(f=>f.id===e.fund_id);
  modal('Modificar gasto',`<p class="wide muted">Se actualizará el saldo de ${esc(fund.name)}. Se conservará el historial. Si es una compra, este ajuste no modifica las existencias.</p><label class="wide">Concepto<input name="description" maxlength="160" value="${esc(e.description)}" required></label><label>Fecha del gasto<input name="occurred_on" type="date" min="${esc(fund.starts_on)}" max="${today()}" value="${esc(e.occurred_on)}" required></label><label>Importe (MXN)<input name="amount" type="number" inputmode="decimal" min="0.01" max="1000000" step="0.01" value="${e.amount_cents/100}" required></label><label>Categoría<select name="category">${options([...new Set([...ctx.categories,e.category])],e.category)}</select></label><label>Medio<select name="method"><option value="card" ${e.method==='card'?'selected':''}>Tarjeta</option>${fund.kind==='voucher'?'':`<option value="cash" ${e.method==='cash'?'selected':''}>Efectivo</option>`}</select></label>`,async f=>{
   const x={id:e.id,version:e.revision||1,description:f.get('description').trim(),amount_cents:cents(f.get('amount')),occurred_on:f.get('occurred_on'),method:f.get('method'),category:f.get('category')};validateExpense(x,fund);await command('expense_edit',x);
  },'Guardar corrección');
 }
 function linkExpense(id){
  const data=ctx.getData(),expense=data.expenses.find(e=>e.id===id);
  if(data.inventory_events.some(v=>v.expense_id===id)){showHistory('Productos ya vinculados','<p>Este gasto ya actualizó existencias. Consulta el historial del producto en Inventario.</p>');return;}
  if(!data.products.length){showHistory('Agrega productos','<p>Primero crea el producto en Inventario; después vuelve al gasto para vincularlo.</p>');return;}
  const row=()=>`<div class="wide expense-product-line"><label>Producto<select name="product_id">${data.products.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} (${esc(p.unit)})</option>`).join('')}</select></label>${numeric('quantity','Unidades que faltan en inventario',1,0.001)}</div>`;
  const d=modal('Productos de '+expense.description,`<p class="wide muted">Este gasto ya descontó dinero. Agrega solo las unidades que realmente conservas y que aún no figuran en Inventario. No se cobrará de nuevo.</p><div class="wide" id="expense-lines">${row()}</div><button class="secondary wide" type="button" id="another-product">+ Otro producto</button>`,async f=>{
   const lines=[...d.querySelectorAll('.expense-product-line')].map(el=>({product_id:el.querySelector('[name="product_id"]').value,quantity:quantity(el.querySelector('[name="quantity"]').value,{zero:false})}));
   if(new Set(lines.map(l=>l.product_id)).size!==lines.length)throw new Error('Selecciona cada producto una sola vez.');
   if(ctx.isDemo())await command('link_expense_items',{expense_id:id,lines});
   else{const {error}=await ctx.db.rpc('link_expense_inventory',{p_household:data.household.id,p_expense:id,p_lines:lines});if(error)throw error;}
  },'Vincular al inventario');
  d.querySelector('#another-product').onclick=()=>d.querySelector('#expense-lines').insertAdjacentHTML('beforeend',row());
 }
 function expenseHistory(id){const rows=ctx.getData().expense_history.filter(x=>x.expense_id===id).sort((a,b)=>b.created_at.localeCompare(a.created_at));showHistory('Historial del gasto',rows.map(x=>`<div class="history-entry"><strong>${esc(x.actor_name)}</strong> · ${esc(new Date(x.created_at).toLocaleString('es-MX'))}<p>Fecha: ${esc(x.before_data.occurred_on)} → ${esc(x.after_data.occurred_on)}<br>Importe: ${money(x.before_data.amount_cents)} → ${money(x.after_data.amount_cents)}<br>Concepto: ${esc(x.before_data.description)} → ${esc(x.after_data.description)}<br>Categoría: ${esc(x.before_data.category)} → ${esc(x.after_data.category)}<br>Medio: ${esc(x.before_data.method)} → ${esc(x.after_data.method)}</p></div>`).join('')||'<p class="muted">Este gasto todavía no tiene correcciones.</p>');}
 function productForm(id){
  const p=id?{...ctx.getData().products.find(p=>p.id===id)}:null;const pid=p?.id||crypto.randomUUID();
  const funds=ctx.getData().funds;
  modal(p?'Editar producto':'Añadir producto',`<label class="wide">Nombre<input name="name" maxlength="120" required value="${esc(p?.name||'')}"></label><label>Categoría<select name="category">${options(categories,p?.category)}</select></label><label>Unidad<select name="unit">${options(['unidad','pieza','paquete','litro','kg','rollo','botella'],p?.unit||'unidad')}</select></label>${p?'<p class="wide muted">Para cambiar existencias utiliza «Registrar consumo / ajuste».</p>':numeric('on_hand','Existencias actuales',0)}${numeric('minimum','Avisar cuando queden',p?.minimum||0)}${numeric('target','Cantidad objetivo',p?.target||0)}${numeric('usual_purchase_quantity','Cantidad habitual de compra',p?.usual_purchase_quantity||1,0.001)}<label>Precio estimado por unidad (MXN)<input name="estimated_price" type="number" min="0" max="1000000" step="0.01" inputmode="decimal" value="${p?.estimated_unit_price_cents==null?'':p.estimated_unit_price_cents/100}"></label><label>Fuente habitual<select name="usual_fund_id"><option value="">Sin preferencia</option>${funds.map(f=>`<option value="${esc(f.id)}" ${p?.usual_fund_id===f.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select></label><label>Se repone cada (días)<input name="recurring_days" type="number" min="1" max="3650" step="1" value="${p?.recurring_days||''}" placeholder="Ej. 7 o 14"></label><label>Día habitual<select name="recurring_weekday"><option value="">Cualquier día</option>${['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map((day,index)=>`<option value="${index+1}" ${Number(p?.recurring_weekday)===index+1?'selected':''}>${day}</option>`).join('')}</select></label><label class="wide remember"><input type="checkbox" name="essential" ${p?.essential?'checked':''}> Es un producto esencial</label>`,async f=>{
   const minimum=quantity(f.get('minimum')),target=quantity(f.get('target'));if(target<minimum)throw new Error('El objetivo no puede ser menor al mínimo.');
   const estimated=f.get('estimated_price');await smartCommand('product_save',{id:pid,version:p?.version??null,name:f.get('name').trim(),category:f.get('category'),unit:f.get('unit'),minimum,target,usual_purchase_quantity:quantity(f.get('usual_purchase_quantity'),{zero:false}),estimated_unit_price_cents:estimated===''?'':cents(estimated),usual_fund_id:f.get('usual_fund_id'),recurring_days:f.get('recurring_days'),recurring_weekday:f.get('recurring_weekday'),essential:f.get('essential')==='on',...(!p?{on_hand:quantity(f.get('on_hand'))}:{})});
  });
 }
 function stockForm(id){const p={...ctx.getData().products.find(p=>p.id===id)};
  modal('Registrar consumo / ajuste',`<p class="wide muted">${esc(p.name)} · Disponible: <strong>${p.on_hand} ${esc(p.unit)}</strong></p><label class="wide">Tipo<select name="type"><option value="consume">Consumo</option><option value="waste">Desperdicio</option><option value="adjust">Corregir existencia total</option></select></label>${numeric('quantity','Cantidad',1)}<label>Nota<input name="note" maxlength="120" placeholder="Opcional"></label>`,async f=>{
   const amount=quantity(f.get('quantity'));const type=f.get('type');const delta=type==='adjust'?amount-p.on_hand:-amount;if(delta===0)throw new Error('La cantidad debe producir un cambio.');if(p.on_hand+delta<0)throw new Error('No puedes descontar más de lo disponible.');await command('stock_adjust',{id:p.id,version:p.version,delta:Math.round(delta*1000)/1000,reason:({consume:'Consumo',waste:'Desperdicio',adjust:'Corrección'})[type]+(f.get('note').trim()?': '+f.get('note').trim():'')});
  });
 }
 function stockHistory(id){const rows=ctx.getData().inventory_events.filter(x=>x.product_id===id).sort((a,b)=>b.created_at.localeCompare(a.created_at));showHistory('Movimientos de inventario',rows.map(x=>`<div class="history-entry"><strong>${esc(x.reason)}</strong><p>${Number(x.delta)>0?'+':''}${x.delta} · Existencia: ${x.balance}<br><small>${esc(x.actor_name)} · ${esc(new Date(x.created_at).toLocaleString('es-MX'))}</small></p></div>`).join('')||'<p>Sin movimientos.</p>');}
 function addShopping(productId){const data=ctx.getData(),products=[...data.products].sort((a,b)=>a.name.localeCompare(b.name)),funds=data.funds;
  const d=modal('Añadir a Mi lista',`<label class="wide">Producto<select name="product_id"><option value="__new__">＋ Producto nuevo</option>${products.map(p=>`<option value="${esc(p.id)}" ${p.id===productId?'selected':''}>${esc(p.name)} (${esc(p.unit)})</option>`).join('')}</select></label><div class="wide form-grid" id="new-product-fields"><label class="wide">Nombre<input name="name" maxlength="120"></label><label>Categoría<select name="category">${options(categories,'Despensa')}</select></label><label>Unidad<select name="unit">${options(['unidad','pieza','paquete','litro','kg','rollo','botella'],'unidad')}</select></label></div>${numeric('quantity','Cantidad',1,0.001)}<label>Precio estimado por unidad<input name="estimated_price" type="number" min="0" max="1000000" step="0.01" inputmode="decimal"></label><label class="wide walmart-toggle"><input type="checkbox" name="walmart_lookup"> Buscar precio publicado en Walmart</label><div class="wide walmart-result" data-walmart-result hidden><p class="notice" data-walmart-status aria-live="polite"></p><label data-walmart-picker hidden>Coincidencia<select data-walmart-matches></select></label><a class="text-link" data-walmart-link href="" target="_blank" rel="noopener noreferrer" hidden>Ver producto en Walmart ↗</a><small>Precio en línea estimado; puede variar por tienda, ubicación y disponibilidad.</small></div><label class="wide">Fuente sugerida<select name="fund_id"><option value="">Elegir después</option>${funds.map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('')}</select></label><p class="wide muted">Agregar no descuenta dinero. El gasto se registra únicamente al finalizar la compra.</p>`,async f=>{const isNew=f.get('product_id')==='__new__';if(isNew&&!f.get('name').trim())throw new Error('Escribe el nombre del producto.');const estimated=f.get('estimated_price');await smartCommand('add',{product_id:isNew?'':f.get('product_id'),new_product_id:isNew?crypto.randomUUID():'',name:f.get('name').trim(),category:f.get('category'),unit:f.get('unit'),quantity:quantity(f.get('quantity'),{zero:false}),estimated_unit_price_cents:estimated===''?'':cents(estimated),fund_id:f.get('fund_id'),priority:'optional',reason:'Agregado manualmente'});});
  const form=d.querySelector('form'),select=form.elements.product_id,fields=d.querySelector('#new-product-fields'),lookup=form.elements.walmart_lookup,result=d.querySelector('[data-walmart-result]'),status=d.querySelector('[data-walmart-status]'),picker=d.querySelector('[data-walmart-picker]'),matchesSelect=d.querySelector('[data-walmart-matches]'),link=d.querySelector('[data-walmart-link]');let lookupSequence=0,lookupTimer;
  const showMatch=(match,fromDemo=false)=>{applyWalmartMatch(form,match);status.className='notice success';status.textContent=`${fromDemo?'Precio de prueba':'Precio encontrado'}: ${match.name} · ${money(match.price_cents)}.`;link.hidden=!match.url;link.href=match.url||'';};
  const searchPrice=async()=>{if(!lookup.checked)return;const query=walmartQueryFor(form,products);result.hidden=false;picker.hidden=true;link.hidden=true;if(query.length<3){status.className='notice';status.textContent='Escribe el nombre del producto para buscar su precio.';return;}const request=++lookupSequence;status.className='notice';status.textContent='Buscando el precio publicado en Walmart…';lookup.disabled=true;try{const response=await findWalmartPrice(ctx.db,query,{demo:ctx.isDemo()});if(request!==lookupSequence)return;const matches=response.matches||[response.match];matchesSelect.innerHTML=matches.map((match,index)=>`<option value="${index}">${esc(match.name)} · ${money(match.price_cents)}</option>`).join('');matchesSelect._matches=matches;picker.hidden=matches.length<2;showMatch(response.match,response.demo);}catch(error){if(request!==lookupSequence)return;status.className='notice error';status.textContent=error.message||'No se pudo consultar Walmart. Captura el precio manualmente.';}finally{if(request===lookupSequence)lookup.disabled=false;}};
  matchesSelect.onchange=()=>showMatch(matchesSelect._matches?.[Number(matchesSelect.value)]||null,ctx.isDemo());
  lookup.onchange=()=>{clearTimeout(lookupTimer);if(lookup.checked)searchPrice();else{lookupSequence++;result.hidden=true;}};
  fields.querySelector('[name="name"]').oninput=()=>{if(!lookup.checked)return;clearTimeout(lookupTimer);lookupTimer=setTimeout(searchPrice,700);};
  const toggle=()=>{fields.hidden=select.value!=='__new__';fields.querySelector('[name="name"]').required=select.value==='__new__';const p=products.find(row=>row.id===select.value);if(p){form.elements.quantity.value=p.usual_purchase_quantity||1;form.elements.estimated_price.value=(p.estimated_unit_price_cents??p.last_unit_price_cents)==null?'':(p.estimated_unit_price_cents??p.last_unit_price_cents)/100;form.elements.fund_id.value=p.usual_fund_id||'';}if(lookup.checked)searchPrice();};select.onchange=toggle;toggle();
 }
 function editShopping(id,forceCart=false){const data=ctx.getData(),item={...data.shopping_items.find(x=>x.id===id)},p=data.products.find(p=>p.id===item.product_id),funds=data.funds;
  const desired=forceCart?'in_cart':item.state;const d=modal(forceCart?'Agregar al carrito':p.name,`${numeric('quantity',`Cantidad real (${esc(p.unit)})`,item.quantity,0.001)}<label>Precio real por ${esc(p.unit)} (MXN)<input name="price" type="number" min="0.01" max="1000000" step="0.01" inputmode="decimal" value="${item.unit_price_cents==null?(item.estimated_unit_price_cents==null?'':item.estimated_unit_price_cents/100):item.unit_price_cents/100}" required></label><label>Fuente de pago<select name="fund_id" required><option value="">Selecciona</option>${funds.map(f=>`<option value="${esc(f.id)}" ${item.fund_id===f.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select></label><label>Medio<select name="payment_method"><option value="card" ${item.payment_method!=='cash'?'selected':''}>Tarjeta</option><option value="cash" ${item.payment_method==='cash'?'selected':''}>Efectivo</option></select></label><label class="wide">Estado<select name="state"><option value="planned" ${desired==='planned'?'selected':''}>Mi lista</option><option value="in_cart" ${desired==='in_cart'?'selected':''}>En carrito</option><option value="skipped">Omitir</option></select></label><p id="item-budget" class="wide notice"></p>`,async f=>{const price=f.get('price'),state=f.get('state'),fundId=f.get('fund_id');if(state==='in_cart'&&(!fundId||price===''||Number(price)<=0))throw new Error('Registra precio y fuente para llevarlo al carrito.');await smartCommand('edit',{id:item.id,version:item.version,quantity:quantity(f.get('quantity'),{zero:false}),unit_price_cents:price===''?'':cents(price),estimated_unit_price_cents:item.estimated_unit_price_cents??'',fund_id:fundId,payment_method:f.get('payment_method'),state});},forceCart?'Agregar al carrito':'Guardar');
  const form=d.querySelector('form'),note=d.querySelector('#item-budget');const enforce=()=>{const fund=funds.find(row=>row.id===form.elements.fund_id.value);if(fund?.kind==='voucher'){form.elements.payment_method.value='card';form.elements.payment_method.querySelector('[value="cash"]').disabled=true;}else form.elements.payment_method.querySelector('[value="cash"]').disabled=false;const price=form.elements.price.value,qty=form.elements.quantity.value;if(fund&&price){const projected=cents(price)*Number(qty),available=ctx.fundSummary(fund).available;note.textContent=projected>available?`Fondos insuficientes en ${fund.name}: faltan ${money(projected-available)}.`:`Disponible en ${fund.name}: ${money(available)}. Después: ${money(available-projected)}.`;}else note.textContent='Elige la fuente para comparar con su disponible real.';};form.elements.fund_id.onchange=enforce;form.elements.price.oninput=enforce;form.elements.quantity.oninput=enforce;enforce();
 }
 async function listAction(action,payload,button){button.disabled=true;try{await smartCommand(action,payload);await refresh();}catch(error){button.disabled=false;showHistory('No se pudo actualizar',`<p>${esc(error.message)}</p>`);}}
 function checkout(){const data=ctx.getData(),breakdown=cartBreakdown(data,ctx.fundSummary),rows=breakdown.cart.map(row=>({...row}));if(!rows.length){showHistory('Carrito vacío','<p>Marca primero los productos que llevas.</p>');return;}const total=breakdown.total;if(total<=0){showHistory('Revisa los precios','<p>El total debe ser mayor a cero.</p>');return;}const id=crypto.randomUUID();
  modal('Finalizar compra',`<div class="wide checkout-review"><div><small>Productos comprados</small><strong>${rows.length}</strong></div>${breakdown.byFund.map(row=>`<div><small>${esc(row.fund.name)}</small><strong>${money(row.spent)}</strong></div>`).join('')}<div><small>Total general</small><strong>${money(total)}</strong></div><div><small>Disponible restante</small><strong class="${breakdown.available-total<0?'negative':''}">${money(breakdown.available-total)}</strong></div></div><label>Fecha<input type="date" name="purchased_on" value="${today()}" max="${today()}" required></label><label>Comercio (opcional)<input name="merchant" maxlength="120" placeholder="Tienda o mercado"></label><p class="wide notice">${budgetMessages(breakdown).map(esc).join('<br>')}</p><p class="wide muted">Al confirmar se crearán los gastos por fuente, se actualizará el inventario y se guardará el historial de precios en una sola operación.</p>`,async f=>smartCommand('checkout',{id,purchased_on:f.get('purchased_on'),merchant:f.get('merchant').trim(),total_cents:total,lines:rows.map(row=>({id:row.id,version:row.version}))}),'Confirmar compra');
 }
 function inventoryView(){const data=ctx.getData(),products=[...data.products].sort((a,b)=>a.name.localeCompare(b.name)),finished=products.filter(p=>stockStatus(p)==='Terminado').length,low=products.filter(p=>stockStatus(p)==='Por terminar').length;return `<div class="section-title"><span class="pill">${products.length} productos · ${finished} terminados · ${low} por terminar</span><button data-action="new-product">+ Añadir producto</button></div><p class="subtle muted">Los mínimos, el consumo y la frecuencia alimentan automáticamente la Lista Inteligente.</p><div class="inventory-grid">${products.map(p=>{const estimate=consumptionEstimate(p,data.inventory_events);return `<article class="card"><div class="section-title"><span class="pill ${stockStatus(p)==='Terminado'?'empty-stock':stockStatus(p)==='Por terminar'?'warning':''}">${stockStatus(p)}</span><button class="text" data-product-edit="${esc(p.id)}">Editar</button></div><h2>${esc(p.name)}</h2><small>${esc(p.category)}</small><div class="amount">${Number(p.on_hand)} <small>${esc(p.unit)}</small></div><p class="subtle muted">Mínimo ${Number(p.minimum)} · Objetivo ${Number(p.target)}${p.last_unit_price_cents!=null?`<br>Último precio ${money(p.last_unit_price_cents)} por ${esc(p.unit)}`:''}${p.recurring_days?`<br>Compra habitual cada ${p.recurring_days} días`:''}${estimate?`<br>Duración estimada: ${estimate.daysLeft} días`:''}</p><div class="product-actions"><button class="secondary" data-stock="${esc(p.id)}">Consumo / ajuste</button><button class="text" data-add-product="${esc(p.id)}">A la lista</button><button class="text" data-stock-history="${esc(p.id)}">Historial</button></div></article>`;}).join('')||'<section class="card empty">Añade lo que tienes en casa para comenzar.</section>'}</div>`;}
 function shoppingView(){const data=ctx.getData(),items=smartItems(data),suggested=items.filter(i=>i.state==='suggested').sort((a,b)=>priorityOrder[a.priority]-priorityOrder[b.priority]),planned=items.filter(i=>i.state==='planned').sort((a,b)=>priorityOrder[a.priority]-priorityOrder[b.priority]),breakdown=cartBreakdown(data,ctx.fundSummary),after=breakdown.available-breakdown.total,ratio=breakdown.available>0?Math.max(0,Math.min(100,after/breakdown.available*100)):0;const product=i=>data.products.find(p=>p.id===i.product_id),fund=i=>data.funds.find(f=>f.id===i.fund_id);
  const suggestion=i=>{const p=product(i),estimated=itemTotal(i,true);return `<article class="smart-suggestion"><div><span class="pill priority-${esc(i.priority)}">${priorityLabel(i.priority)}</span><h3>${esc(p.name)}</h3><small>${Number(i.quantity)} ${esc(p.unit)} · ${esc(i.reason||'Sugerencia automática')}</small><small>${estimated==null?'Precio por definir':money(estimated)+' estimados'} · ${esc(fund(i)?.name||'Fuente por elegir')}</small></div><div class="smart-actions"><button data-suggest-add="${esc(i.id)}">Agregar</button><button class="text" data-smart-skip="${esc(i.id)}">Omitir</button></div></article>`;};
  const row=i=>{const p=product(i),total=itemTotal(i,i.state!=='in_cart');return `<div class="shopping-row"><button class="cart-check ${i.state==='in_cart'?'checked':''}" ${i.state==='in_cart'?`data-cart-remove="${esc(i.id)}"`:`data-cart-add="${esc(i.id)}"`} aria-label="${i.state==='in_cart'?'Sacar':'Agregar'} ${esc(p.name)} ${i.state==='in_cart'?'del':'al'} carrito">${i.state==='in_cart'?'✓':'+'}</button><div class="row-main"><strong>${esc(p.name)}</strong><small>${Number(i.quantity)} ${esc(p.unit)} · ${priorityLabel(i.priority)}</small><small>${i.state==='in_cart'?`${money(i.unit_price_cents)} por ${esc(p.unit)} · ${esc(fund(i)?.name||'Sin fuente')}`:`${total==null?'Precio estimado pendiente':money(total)+' estimados'} · ${esc(i.reason||'Agregado manualmente')}`}</small></div><div class="row-amount"><strong>${total==null?'—':money(total)}</strong><br><button class="text" data-shopping-edit="${esc(i.id)}">Editar</button></div></div>`;};
  return `<section class="smart-budget"><div><small>Disponible utilizable</small><strong>${money(breakdown.available)}</strong></div><div><small>Compra actual</small><strong>${money(breakdown.total)}</strong></div><div><small>Después de comprar</small><strong class="${after<0?'negative':''}">${money(after)}</strong></div><div class="budget-meter" aria-label="${Math.round(ratio)} por ciento del presupuesto permanece"><i style="width:${ratio}%"></i></div><p>${budgetMessages(breakdown).map(esc).join(' · ')}</p></section><div class="section-title smart-heading"><div><span class="eyebrow">Inventario + presupuesto</span><h2>Lista Inteligente</h2></div><button data-action="add-shopping">+ Añadir manualmente</button></div><section class="smart-section"><div class="section-title"><div><h2>Sugeridos para comprar</h2><p class="muted">Detectados por existencias y frecuencia.</p></div><button class="secondary" data-action="add-all-suggested" ${suggested.length?'':'disabled'}>Agregar todos</button></div><div class="smart-suggestions">${suggested.map(suggestion).join('')||'<div class="empty">No hay sugerencias pendientes.</div>'}</div></section><section class="card smart-section"><div class="section-title"><h2>Mi lista</h2><span class="pill">${planned.length} productos</span></div>${planned.map(row).join('')||'<div class="empty">Agrega una sugerencia o un producto manual.</div>'}</section><section class="card smart-section"><div class="section-title"><h2>En carrito</h2><span class="pill">${breakdown.cart.length} productos</span></div>${breakdown.cart.map(row).join('')||'<div class="empty">Marca un producto cuando lo pongas físicamente en el carrito.</div>'}<div class="fund-split">${breakdown.byFund.map(r=>`<div><small>${esc(r.fund.name)} utilizada</small><strong>${money(r.spent)}</strong><span class="${r.after<0?'negative':''}">Quedaría ${money(r.after)}</span></div>`).join('')}</div><button class="full finalize" data-action="checkout" ${breakdown.cart.length?'':'disabled'}>Finalizar compra · ${money(breakdown.total)}</button></section>${purchaseHistoryView()}`;}
 function purchaseHistoryView(){const data=ctx.getData(),rows=[...(data.purchases||[])].sort((a,b)=>b.purchased_on.localeCompare(a.purchased_on)).slice(0,5);return `<section class="smart-section"><div class="section-title"><h2>Compras recientes</h2><span class="pill">Detalle por artículo</span></div><div class="card">${rows.map(p=>`<div class="row"><div class="row-main"><strong>${esc(p.merchant||'Compra del hogar')}</strong><small>${esc(p.purchased_on)} · ${p.item_count} artículos</small></div><div class="row-amount"><strong>${money(p.total_cents)}</strong><br><button class="text" data-purchase-history="${esc(p.id)}">Ver detalle</button></div></div>`).join('')||'<div class="empty">Aquí aparecerán las compras finalizadas.</div>'}</div></section>`;}
 function purchaseHistory(id){const data=ctx.getData(),purchase=data.purchases.find(row=>row.id===id),rows=data.expense_items.filter(row=>row.purchase_id===id);showHistory('Detalle de '+(purchase.merchant||'la compra'),`<p class="muted">${esc(purchase.purchased_on)} · ${rows.length} artículos</p>${rows.map(row=>`<div class="history-entry"><strong>${esc(row.product_name)}</strong><p>${Number(row.quantity)} ${esc(row.unit)} × ${money(row.unit_price_cents)} = <strong>${money(row.total_cents)}</strong><br>${esc(data.funds.find(f=>f.id===row.fund_id)?.name)} · ${row.method==='cash'?'Efectivo':'Tarjeta'}</p></div>`).join('')}<div class="row"><strong>Total</strong><strong>${money(purchase.total_cents)}</strong></div>`);}
 function bind(){
  const bindAll=(selector,fn)=>document.querySelectorAll(selector).forEach(b=>b.onclick=()=>fn(b));
  bindAll('[data-expense-stock]',b=>linkExpense(b.dataset.expenseStock));bindAll('[data-expense-edit]',b=>editExpense(b.dataset.expenseEdit));bindAll('[data-expense-history]',b=>expenseHistory(b.dataset.expenseHistory));
  bindAll('[data-product-edit]',b=>productForm(b.dataset.productEdit));bindAll('[data-stock]',b=>stockForm(b.dataset.stock));bindAll('[data-stock-history]',b=>stockHistory(b.dataset.stockHistory));bindAll('[data-add-product]',b=>addShopping(b.dataset.addProduct));
  bindAll('[data-shopping-edit]',b=>editShopping(b.dataset.shoppingEdit));bindAll('[data-cart-add]',b=>editShopping(b.dataset.cartAdd,true));
  bindAll('[data-cart-remove]',b=>{const item=ctx.getData().shopping_items.find(row=>row.id===b.dataset.cartRemove);listAction('edit',{id:item.id,version:item.version,quantity:item.quantity,unit_price_cents:item.unit_price_cents??'',estimated_unit_price_cents:item.estimated_unit_price_cents??'',fund_id:item.fund_id||'',payment_method:item.payment_method||'card',state:'planned'},b);});
  bindAll('[data-suggest-add]',b=>listAction('add_suggested',{id:b.dataset.suggestAdd},b));
  bindAll('[data-smart-skip]',b=>{const item=ctx.getData().shopping_items.find(row=>row.id===b.dataset.smartSkip);listAction('edit',{id:item.id,version:item.version,quantity:item.quantity,unit_price_cents:item.unit_price_cents??'',estimated_unit_price_cents:item.estimated_unit_price_cents??'',fund_id:item.fund_id||'',payment_method:item.payment_method||'card',state:'skipped'},b);});
  bindAll('[data-purchase-history]',b=>purchaseHistory(b.dataset.purchaseHistory));
  bindAll('[data-action]',b=>({'new-product':()=>productForm(),'add-shopping':()=>addShopping(),'add-all-suggested':()=>listAction('add_suggested',{},b),'checkout':checkout}[b.dataset.action]?.()));
 }
 return {inventoryView,shoppingView,bind};
}
